### ISSUE TITLE
Rails3 deprecation warning

### ISSUE THREAD

**Issue by millisami** [kaievns/right-rails#12]
I'm using the latest right-rails from git repo for a rails3 app.
This is just to inform you to patch the warning regarding that RAILS_ENV
        DEPRECATION WARNING: RAILS_ENV is deprecated! Use Rails.env instead. (called from rightjs_scripts at
        /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@automation/bundler/gems/
        right-rails-31e116387439ab0e3214eef55f316e6da35920f3-master/lib/right_rails/helpers/basic.rb:26)

**Comment by kaievns** [comment]
Yes, I know about that. I use the constant for now because of the specs, will switch to the `Rails` constant with Rails3 support

**Comment by kaievns** [comment]
it's all cool with version 1.0.0 now
