### ISSUE TITLE
Uploader plugin with Rails3

### ISSUE THREAD

**Issue by adie** [kaievns/right-rails#15]
Hi! In Rails 3 we doesn't have remote_form_tag anymore, so info on the wiki for uploading is wrong.
But making form_for with :remote => true does not load rightjs uploader.

P.S.: Link to wiki in README is old, pls update it

**Comment by kaievns** [comment]
Thanks, will check it out

**Comment by kaievns** [comment]
Rails 3 uses another approach with UJS, which we handle inside of the `rails.js`, so there should be nothing in the forms themselves
