### ISSUE TITLE
= javascript_include_tag :defaults, :cache => true

### ISSUE THREAD

**Issue by anlek** [kaievns/right-rails#16]
It seems passing :cache => true (or any hash at the end) throws this error:
    undefined local variable or method `modules' for #<#Class:0x10ca81490:0x10ca7def8>

Backtrace:
    right-rails (1.0.10) lib/right_rails/helpers/rails.rb:12:in `javascript_include_tag'
    app/views/layouts/application.html.haml:15:in`_app_views_layouts_application_html_haml___1950910485_2253631400_0'

**Comment by kaievns** [comment]
Closed by 018c894abe5b9c8d7e2ab2d2a4c2a7a2c472f261 the :cache =&gt; true option fix for the javascript_inclue_tag helper

**Comment by kaievns** [comment]
Hi there,

Finally took care of the bug. Now it should be working just fine in the `1.1.0` release.

Plus now it supports our fancy new CDN!
