### ISSUE TITLE
right-rails+activescaffold

### ISSUE THREAD

**Issue by danil-z** [kaievns/right-rails#17]
Hi folks
Is it possible use right-rails with activescaffold(vhochstein fork for rails 3) plugin without jquery or prototype?

**Comment by kaievns** [comment]
Hi there,

Honestly never tried, but if it's basically a version of rails, then I suppose it should be working. Most of the stuff in right-rails are just plain helpers and shouldn't cause any troubles.

Not sure about the generators though.

**Comment by kaievns** [comment]
seems it's all in here
