### ISSUE TITLE
Broken link_to with :method => :delete

### ISSUE THREAD

**Issue by motiv** [kaievns/right-rails#18]
Not working links If use image_tag in link_to with :method => :delete
Working fine if use plain text

Ребят, не работает ссылка на удаление если внутри картинка. Точнее изредка работает. Если использовать текст - все отлично

**Comment by kaievns** [comment]
why would you need an image inside of a link? :) you always can add an icon with css, which is much more civilized and flexible

```
a {
  padding-left: 16px;
  background: url(../some/img.png) no-repeat left center;
}
```

Or, if you don't need a text, you can hide it with some indentation

```
a {
    text-indent: -9999em;
    outline: none;
    display: inline-block;
    *display: inline;
    *zoom: 1
    width: 16px;
    height: 16px;
    background: url(.....) no-repeat left center;
}
```

Will patch the rails.js module tomorrow though.

**Comment by kaievns** [comment]
Just published a fix, please grab the new version at http://rightjs.org/plugins/rails
