### ISSUE TITLE
RR.update_flash("message") not working

### ISSUE THREAD

**Issue by anlek** [kaievns/right-rails#20]
Update_flash seems not to be working as expected.
calling "RR.update_flash("message")" just remove the <div id="flashes" style="display: none"></div>  div without filling in the message.

I am using the <%= flashes %> that right-rails provides.

**Comment by kaievns** [comment]
I believe it should be a a full string with the `div#flash` structure, not just a message text

**Comment by anlek** [comment]
any chance we can get something like this into the RR module (of course after you do your magic refactoring):

```
RR.Flash = new Class({
  initialize: function(Options) {
    this.Options = Options;
  },
  notice: function(msg) {
    return this.update('notice', msg);
  },
  error: function(msg) {
    return this.update('error', msg);
  },
  update: function(level, msg) {
    var element, flash_element;
    flash_element = $(this.Options.flashId);
    element = flash_element.first($("." + level));
    if (!element) {
      element = this.generate_element(level, flash_element);
    }
    if (element) {
      element.html(msg);
    }
    flash_element.show();
    RR.hide_flash();
    return this;
  },
  generate_element: function(level, parent) {
    var e;
    e = new Element("div", {
      "class": level
    });
    parent.insert(e);
    return e;
  }
});
RR.flash = new RR.Flash(RR.Options);
```

**Comment by kaievns** [comment]
I don't see many people would need that. I mean it's cool, but you normally just reuse the `flashes` helper and this way all the customizations and stuff will be in one place and you don't delegate any structural knowledge to the javascript side.

**Comment by anlek** [comment]
I see what you're saying, however the only assumption I'm making is that user will be using the same structure that the method `flashes` uses. If a user overwrite `flashes`, I'd foresee needing to overwrite the `RR.flash` class as well (or just not using it). But that's just my 2 cents ;)

**Comment by kaievns** [comment]
No, not really, `RR.update_flash` is simply replaces an element by ID, which means whatever you change in the `flashes` won't affect the `RR`. The ID and Fx are also configurable in the `RR.Options` object.
