### ISSUE TITLE
link_to_lightbox inserts unnecessary <script></script> if used for html content

### ISSUE THREAD

**Issue by amdest** [kaievns/right-rails#21]
Hi, Nik.

Tried to use `link_to_lightbox` helper to display an html content.
It shows content as intended.
But also gives the «Parse error» in dev console.
It happens after lightbox rendering finishes:  `<script>html content goes here also and gives an error</script>` is inserted between the `</body>` and `</html>` closing tags.

Take a look at the [screenshot](https://skitch.com/amdest/fsk8s/link-to-lightbox-error).

If used to display images — that error not happening.
But in some cases, large image got incorrect proportions computed — it shows up with _width=height_.

Anyways, thanks for such a great lib!

**Comment by kaievns** [comment]
что-то странное, врятли это `link_to_lightbox`, он просто делает `rel="lightbox"` чистый лайтбокс так же работает на rightjs.org скорее всего это что-то в ваших скриптах

**Comment by amdest** [comment]
В том-то и дело. Я тоже удивился. Никаких скриптов нет: только-только начата разработка. Подключены только `:defaults` и дополнительно `I18n/ru.js`, так как автоматически он не подключился...

Код вызова: `=link_to_lightbox "Текст ссылки", "/welcome/blank", :title => "Текст заголовка и подсказки"`
Где `/welcome/blank` — страница с одним только параграфом.
Применено `layout proc{ |c| c.request.xhr? ? false : "application" }` в `application_controller.rb`, но это никак не влияет на происходящее (то есть — ошибка присутствует и без этого).

Так же, если передать параметр `:remote => true` — то появляется два блока `<script>...</script>` и, соответственно, — две ошибки.

Хотя, повторюсь, при этом всё отображается как и должно: лайтбокс появляется, все контролы работают и т.п.

Забыл добавить: используется релиз Rails 3.1.

**Comment by kaievns** [comment]
похоже тогда что-то внутри ответа с сервера

**Comment by kaievns** [comment]
всмысле в вашем `/welcome/blank`

**Comment by amdest** [comment]
Контроллер `welcome_controller.rb` используется как заглушка для демонстрации дизайна. Там нет даже стандартных CRUD.

Конкретно для `blank`:

```
def blank
end
```

 Нет модели. В хелперах только смена локали прописана.

Это всё.

Лог в терминале:

Started GET "/welcome/blank" for 127.0.0.1 at 2011-09-04 17:36:31 +0400
  Processing by WelcomeController#blank as JS
Rendered welcome/blank.haml (0.2ms)
Completed 200 OK in 32ms (Views: 30.7ms | ActiveRecord: 0.0ms)

`/welcome/blank` обрабатывается как JS, хотя нигде ничего специфичного не запрашивается. Этот контроллер — пустой, как я и написал.

Вот, что у меня в `/app/views/welcome/blank.haml`:

```
.main
  %p Образец
```

Тот же запрос, но на картинку — обрабатывается как запрос на картинку. И ошибки не появляются.

**Comment by kaievns** [comment]
естественно как JS обрабатывается это же ajax запрос, попробуйте явно указать text/html в welcome#blank

``` ruby
def blank
  render :content_type => 'text/html'
end
```

**Comment by amdest** [comment]
Ничего не даёт, к сожалению.
Видимо, что-то в 3.1 в этом плане изменили.

**Comment by kaievns** [comment]
Возможно, но проблемы это не меняет. Скорее всего где-то на стороне рельсы что-то оборачивает ваш респонс в `SCRIPT`, нужно как-то его заставить рельсу отдавать все в чистом хтмл и с корректным content-type.

Либо как-то иначе делать запрос на сервер, например вручную делать AJAX с evalScripts: false или как-то так.

В любом случае, это не похоже на багу right-rails

**Comment by amdest** [comment]
Вот какую закономерность увидел: если не указывать ссылку — то в лайтбоксе отображается текущая страница (естесственно):
`=link_to_lightbox "Текст ссылки", "", :title => "Текст заголовка и подсказки"`
Но ошибки нет.

Вернее, секция `<script></script>` вставляется, но она пустая. Соответственно — ошибки парсера нет.

Но, при указании любой непустой ссылки — ошибка повторяется, так как тогда контент дублируется в секции `<script></script>`.

И ещё: если использовать `:layout => false` — всё повторяется независимо от того указана ссылка, или нет.

В общем — намудрили что-то хлопцы...
