### ISSUE TITLE
rte.js has old path to the rte.png

### ISSUE THREAD

**Issue by amdest** [kaievns/right-rails#23]
There are two places, where the path defined.
First occurrence has been updated to `/assets/rightjs-ui/rte.png` correctly.
But the second one still has `/images/rightjs-ui/rte.png`

So, in production this causes rte-toolbar displayed incorrectly.

It's not a bug, actually, as `rte-src.js` has correct paths.
Just wanted you to know.

**Comment by kaievns** [comment]
thanks for letting me know about the bug! I'll check it on the weekend, probably some regex issue in the scripts patcher for `right-rails`

**Comment by amdest** [comment]
No problem!
I like the principles you use in web development.
RightJS was chosen mainly by my sixth sense at the beginning (as I'm not a developer at all) and by my wish to support domestic developers, but the further i go — the more i like using it.

Thanks!
(Sorry, pressed the wrong button and closed the issue).

**Comment by kaievns** [comment]
I believe this one was fixed

**Comment by amdest** [comment]
I'm sorry not closing the ticket, of course this was fixed.
