### ISSUE TITLE
Feature request: 'data-disable-with' attribute handling

### ISSUE THREAD

**Issue by amdest** [kaievns/right-rails#24]
Can this be implemented for remote links and forms?
It would be a nice addition.

Unfortunately, I'm just a regular user with little programming experience and I was unable to make it myself by hooking a `replace()` to element in `add_xhr_events` or global `submit` event listener in `rails.js` if the `data-disable-with` attribute is present.

Found the following [commit](https://github.com/rails/jquery-ujs/commit/6e9a06d45eaf2da1036d4c2ead25ff57d0127d03) to `jquery-ujs` which shows how was this implemented for remote links, but still no success at my site...

I'm almost positive, it wouldn't be a tough quest for You.
;)

**Comment by kaievns** [comment]
could you write a bit about what it does so i didn't screw it up? btw, is that a standard rails feature or some jquery own feature?

**Comment by amdest** [comment]
When we have remote link or form, we can add `:disable_with => "Wait please..."` to link or submit button's options.
Rails converts this to `data-disable-with="Wait please..."` in HTML.
When link or form processed via xhr — the link/button gets disabled (with inner HTML replaced by the text specified), so it cannot be pressed twice before request is done.

I'm not sure it's Rails standard, but Rails does converts `:disable_with => "Wait please..."` to `data-disable-with="Wait please..."` in HTML, even without jQuery usage...

**Comment by kaievns** [comment]
okay I see. it shouldn't be a problem I'll check what I can do on the weekend

**Comment by amdest** [comment]
Thanks!
It's not a demand though. But would be nice to.

**Comment by kaievns** [comment]
hey there, sorry for a bit of a delay, been busy lately.

I've cooked the patch https://github.com/rightjs/rightjs-plugins/commit/4a9f55f92f9019895ce6d54d4301c4fe646d52f6

will update the modules and the gem a bit later

**Comment by amdest** [comment]
Hi, Nik!

Thanks for this patch, will try it in action asap.

**Comment by kaievns** [comment]
cool, let me know if everything is okay and i'll bundle it up with a new gem update

**Comment by amdest** [comment]
Nikolay, just tested it.

Works as expected for both remote links and remote form submit buttons, thanks!
