### ISSUE TITLE
Sortable.js: CSRF token verify failing

### ISSUE THREAD

**Issue by amdest** [kaievns/right-rails#25]
Hi, Nik.

Same thing as we discussed before and that was fixed by `c1a2a189ce8d44c63e46e7e738366eb7ade75634`, but this time it's in `sortable` module.

Thanks.

**Comment by kaievns** [comment]
Hi there,

I see. It should probably set the CSRF token globally into the `Xhr.Options.params` hash. Try something like this for now

``` javascript
$(document).on('ready', function() {
  var param  = $$('meta[name=csrf-param]')[0],
      token  = $$('meta[name=csrf-token]')[0];

  Xhr.Options.params[param] = token;
});
```

That should help

**Comment by amdest** [comment]
Copy/paste didn't work...

But setting the token inplace, while initialising the Sortable widget like this did the trick:

``` javascript
  new Sortable('pages', {
    url: '/pages/%{id}.js',
    parseId: false,
    Xhr: {
      evalScripts: true,
      params: {
        authenticity_token: '#{form_authenticity_token}'
      }
    }
  });


Thanks.

```

**Comment by kaievns** [comment]
Hi. I've made a bunch of adjustments to the `rails.js` file, could you check it out when you have a minute?

https://github.com/rightjs/rightjs-plugins/commit/2168d7a69baadef300c8b566cdeb83d3b3d13945
