### ISSUE TITLE
Encoding issue with Ruby 1.9.x

### ISSUE THREAD

**Issue by amoeba** [kaievns/right-rails#3]
right-rails is working fine with 1.8.7 but not with 1.9.1. 

Error log: http://gist.github.com/349394

It looks like this is just a 1.8 vs 1.9 file encoding difference. Ruby interprets the files as US-ASCII where they are really Unicode.

**Comment by kaievns** [comment]
Thanks for letting me know, will fix it tomorrow

**Comment by kaievns** [comment]
Closed by e48136c1aee2bf25f3bbbb5c3ce94ab4ae992f71 ruby 1.9.1 encoding issue with the rater plugin
