### ISSUE TITLE
ajaxify new form show

### ISSUE THREAD

**Issue by millisami** [kaievns/right-rails#4]
Hi, I've this in the view!
    <% title "Right-Rails Demo Blog" -%>
    <h1>Listing posts</h1>
    <div id="posts">
      <%= render @posts %>
    </div>
    <br />
    <div id="new_post_container"></div>
    <%= link_to 'New post', new_post_path %>
What I want is to open up the form inside the div `new_post_container` when the 'New post' link is clicked?
Is there any predefined method to achieve this?
I tried as `<%= link_to "New post", "#", :onclick => rjs[:new_post_container].update("New content pusthed.") %>` and it does work/replace the content but it is obtrusive coz the js is printed inside the anchor element.

**Comment by kaievns** [comment]
Mmm why don't you render your content inside the container from the beginning, and then simply toggle its visibility with the link? You can do that unobtrusively from your application.js if you like.

btw: could you post those questions on the rightjs group at google groups?

**Comment by millisami** [comment]
Well I tried to post to google groups, but it says 
"Discussions aren't available right now. We're sorry. Try again shortly."
So, continuing here.

Well I saw all the provided functions in right-rails but couldn't find one for that.
I tried with the following:
    <%= link_to_function "Add New Post" { |page| page[:posts].insert(render(Post.new)) } %>

But got the error:
    SyntaxError in Posts#index

```
Showing app/views/posts/index.html.erb where line #10 raised:

compile error
/home/millisami/rails_apps/right-rails-test/app/views/posts/index.html.erb:10: syntax error, unexpected '{', expecting ')'
...k_to_function "Add New Post" { |page| page[:posts].insert(re...
                              ^
/home/millisami/rails_apps/right-rails-test/app/views/posts/index.html.erb:10: syntax error, unexpected '}', expecting ')'
...ts].insert(render(Post.new)) } ).to_s); @output_buffer.conca...
```

Isn't there the provided method to do that?

**Comment by kaievns** [comment]
You have a syntax error. you should use brackets when you call a function with a block

`link_to_function("Boo"){ |p| }`

**Comment by kaievns** [comment]
but I meant something else. you could implement your case like that

<pre><code>&lt;div id="new_post_container" style="display:none">
  &lt;%= render(Post.new) %>
&lt;/div>

<%= link_to "Toggle form", "#", :id => "toggle_form" %>
</code></pre>

Then in your `application.js` or in some inlined javascript call it like that

<pre><code>$('toggle_form').onClick(function(event) {
  event.stop();
  $('new_post_container').toggle('slide');
});
</code></pre>

**Comment by millisami** [comment]
Thanks, its what I wanted.
I still have some questions/features to ask. I'll post in google groups.
