### ISSUE TITLE
Is it rails3 compatible?

### ISSUE THREAD

**Issue by millisami** [kaievns/right-rails#5]
Hi, does this gem works with Rails3 beta2?

**Comment by kaievns** [comment]
It already has the UJS module worked on beta, didn't try on beta2 yet.

**Comment by millisami** [comment]
I looked at the wiki but couldn't figure out how to use UJS module.
Can you plz explain how to use that UJS module with rails3?

**Comment by kaievns** [comment]
You don't need to do anything, it's already embedded in the `rails.js` file if you use the `rightjs_includes` helper to manage your javascript modules it all should be working right away

**Comment by millisami** [comment]
Thanks, I'll try it out.
