### ISSUE TITLE
update_flash does not work

### ISSUE THREAD

**Issue by luxflux** [kaievns/right-rails#7]
with rais 3 beta3 following code doesnt work:

<code>
<% update_page do |page| %>
<%= raw page.update_flash("Test: #{Time.now.to_s}") %>
<% end %>
</code>
changing update_flash in java_script_generator.rb to the following fixes it:
<code>
def update_flash(content=nil)
  return_value = self.RR.update_flash(content || @util.template.flashes)
  @util.template.flash.clear
  return return_value
end
</code>

**Comment by kaievns** [comment]
Hmmm. It not supposed to be called like that, I guess it should be something like this

```
<%= update_page do |page|
  page.update_flash("Some content")
%>
```
