### ISSUE TITLE
It would be better to have a demo app?

### ISSUE THREAD

**Issue by millisami** [kaievns/right-rails#9]
Hi @madrabbit,
I tried to use the features like autocomplete_field, autocomplete_result, etc ... helpers.

I get always lost and confused with what should be the associations, routing, etc... when I try to implement with multi-model relations.

The examples shown is rather too simple and straightforward that suits for app like blog, comments.

Ain't it be nice to put up an example/demo app which can be referenced to work with right-rails still much faster for moderate/new rails developers?

**Comment by kaievns** [comment]
A good idea, will try to cook something on the weekend

**Comment by kaievns** [comment]
Here you go!

http://github.com/MadRabbit/right-rails-demo

**Comment by millisami** [comment]
Thanks for the demo app.
Will look into it.
